services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: test
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: "pip install -r requirements.txt"
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: "export PATH=$PATH:/usr/local/python3/bin && pip install gunicorn && gunicorn src app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
        